# Generated by Django 3.0.5 on 2020-04-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connect',
        ),
    ]
