# Generated by Django 3.0.5 on 2020-05-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Picture',
            new_name='Profiles_Picture',
        ),
    ]
