# Generated by Django 3.0.5 on 2020-05-05 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200505_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles_picture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
