# Generated by Django 3.0.5 on 2020-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200508_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='/media/profile_pics/red.png', max_length=155),
        ),
    ]
