# Generated by Django 3.0.5 on 2020-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200508_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles_picture',
            name='title',
            field=models.CharField(default='Image_Profile', max_length=155),
        ),
    ]
