# Generated by Django 3.0.5 on 2020-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_profiles_picture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles_picture',
            name='required_level',
            field=models.IntegerField(default=1),
        ),
    ]
